# Implementation of classic arcade game Pong

import simplegui
import random

# initialize globals - pos and vel encode vertical info for paddles
WIDTH = 600
HEIGHT = 400       
BALL_RADIUS = 20
PAD_WIDTH = 8
PAD_HEIGHT = 80
HALF_PAD_WIDTH = PAD_WIDTH / 2
HALF_PAD_HEIGHT = PAD_HEIGHT / 2
LEFT = False
RIGHT = True
ball_pos = [0,0]
ball_vel = [0,0]
left_paddle_pos = [PAD_WIDTH / 2, HEIGHT / 2]
right_paddle_pos = [WIDTH - PAD_WIDTH / 2, HEIGHT / 2]
left_paddle_vel = 0
right_paddle_vel = 0
PADDLE_VEL = 5
score1 = 0
score2 = 0
# initialize ball_pos and ball_vel for new bal in middle of table
# if direction is RIGHT, the ball's velocity is upper right, else upper left
def spawn_ball(direction):
        global ball_pos, ball_vel # these are vectors stored as lists
            vel_hor = random.randrange(120, 240) / 100.0
                vel_ver = random.randrange(60, 180) / 100.0

                    ball_pos[0] = WIDTH / 2
                        ball_pos[1] = HEIGHT/ 2
                            if (direction == RIGHT):
                                        ball_vel[0] = vel_hor
                                            else:
                                                        ball_vel[0] = vel_hor * -1
                                                            ball_vel[1] = vel_ver * -1
                                                                    
                                                                    # define event handlers
                                                                    def new_game():
                                                                            global left_paddle_pos, right_paddle_pos, left_paddle_vel, right_paddle_vel  # these are numbers
                                                                                global score1, score2  # these are ints
                                                                                    left_paddle_pos = [PAD_WIDTH / 2, HEIGHT / 2]
                                                                                        right_paddle_pos = [WIDTH - PAD_WIDTH / 2, HEIGHT / 2]
                                                                                            left_paddle_vel = 0
                                                                                                right_paddle_vel = 0
                                                                                                    score1 = 0
                                                                                                        score2 = 0
                                                                                                            
                                                                                                                dir = random.randrange(0,2)
                                                                                                                    if (dir == 0):
                                                                                                                                spawn_ball(LEFT)
                                                                                                                                    else:
                                                                                                                                                spawn_ball(RIGHT)
                                                                                                                                                    
                                                                                                                                                    def draw(canvas):
                                                                                                                                                            global score1, score2, paddle1_pos, paddle2_pos, ball_pos, ball_vel
                                                                                                                                                             
                                                                                                                                                                     
                                                                                                                                                                         # draw mid line and gutters
                                                                                                                                                                             canvas.draw_line([WIDTH / 2, 0],[WIDTH / 2, HEIGHT], 1, "White")
                                                                                                                                                                                 canvas.draw_line([PAD_WIDTH, 0],[PAD_WIDTH, HEIGHT], 1, "White")
                                                                                                                                                                                     canvas.draw_line([WIDTH - PAD_WIDTH, 0],[WIDTH - PAD_WIDTH, HEIGHT], 1, "White")
                                                                                                                                                                                             
                                                                                                                                                                                                 # update ball
                                                                                                                                                                                                     ball_pos[0] = ball_pos[0] + ball_vel[0]
                                                                                                                                                                                                         ball_pos[1] = ball_pos[1] + ball_vel[1]
                                                                                                                                                                                                             if (ball_pos[1] - BALL_RADIUS <= 0):
                                                                                                                                                                                                                         ball_vel[1] = ball_vel[1] * -1
                                                                                                                                                                                                                             elif (ball_pos[1] + BALL_RADIUS >= HEIGHT):
                                                                                                                                                                                                                                         ball_vel[1] = ball_vel[1] * -1
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               # draw ball
                                                                                                                                                                                                                                                                                   canvas.draw_circle(ball_pos,BALL_RADIUS / 2,BALL_RADIUS, "white")
                                                                                                                                                                                                                                                                                       # update paddle's vertical position, keep paddle on the screen
                                                                                                                                                                                                                                                                                           new_pos = left_paddle_pos[1] + left_paddle_vel
                                                                                                                                                                                                                                                                                               if (new_pos >= PAD_HEIGHT / 2) and (new_pos <= HEIGHT - PAD_HEIGHT / 2):
                                                                                                                                                                                                                                                                                                           left_paddle_pos[1] = new_pos
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                   new_pos = right_paddle_pos[1] + right_paddle_vel
                                                                                                                                                                                                                                                                                                                       if (new_pos >= PAD_HEIGHT / 2) and (new_pos <= HEIGHT - PAD_HEIGHT / 2):
                                                                                                                                                                                                                                                                                                                                   right_paddle_pos[1] = new_pos
                                                                                                                                                                                                                                                                                                                                       # draw paddles
                                                                                                                                                                                                                                                                                                                                           canvas.draw_line([left_paddle_pos[0], left_paddle_pos[1] + PAD_HEIGHT / 2],
                                                                                                                                                                                                                                                                                                                                                                        [left_paddle_pos[0], left_paddle_pos[1] - PAD_HEIGHT / 2], 
                                                                                                                                                                                                                                                                                                                                                                                             PAD_WIDTH, "white")
                                                                                                                                                                                                                                                                                                                                               canvas.draw_line([right_paddle_pos[0], right_paddle_pos[1] + PAD_HEIGHT / 2],
                                                                                                                                                                                                                                                                                                                                                                            [right_paddle_pos[0], right_paddle_pos[1] - PAD_HEIGHT / 2], 
                                                                                                                                                                                                                                                                                                                                                                                                 PAD_WIDTH, "white")
                                                                                                                                                                                                                                                                                                                                                   # determine whether paddle and ball collide    
                                                                                                                                                                                                                                                                                                                                                       if (ball_pos[0] - BALL_RADIUS <= PAD_WIDTH):
                                                                                                                                                                                                                                                                                                                                                                   if (ball_pos[1] >= left_paddle_pos[1] - HALF_PAD_HEIGHT and 
                                                                                                                                                                                                                                                                                                                                                                                   ball_pos[1] <= left_paddle_pos[1] + HALF_PAD_HEIGHT):
                                                                                                                                                                                                                                                                                                                                                                                   ball_vel[0] = ball_vel[0] * -1.1
                                                                                                                                                                                                                                                                                                                                                                                           else:
                                                                                                                                                                                                                                                                                                                                                                                                           score2 += 1
                                                                                                                                                                                                                                                                                                                                                                                                                       spawn_ball(RIGHT)
                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                       elif (ball_pos[0] + BALL_RADIUS >= WIDTH - PAD_WIDTH):
                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (ball_pos[1] >= right_paddle_pos[1] - PAD_HEIGHT / 2 and 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ball_pos[1] <= right_paddle_pos[1] + PAD_HEIGHT / 2):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ball_vel[0] = ball_vel[0] * -1.1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           score1 += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       spawn_ball(LEFT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # draw scores
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           canvas.draw_text(str(score1),(20,30),30,"white")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               canvas.draw_text(str(score2),(WIDTH - 30, 30), 30, "white")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               def keydown(key):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       global left_paddle_vel, right_paddle_vel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if key == simplegui.KEY_MAP["up"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       right_paddle_vel = right_paddle_vel - PADDLE_VEL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           elif key == simplegui.KEY_MAP["down"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       right_paddle_vel = right_paddle_vel + PADDLE_VEL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           elif key == simplegui.KEY_MAP["w"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       left_paddle_vel = left_paddle_vel - PADDLE_VEL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           elif key == simplegui.KEY_MAP["s"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       left_paddle_vel = left_paddle_vel + PADDLE_VEL

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       def keyup(key):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               global left_paddle_vel, right_paddle_vel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if key == simplegui.KEY_MAP["up"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               right_paddle_vel = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   elif key == simplegui.KEY_MAP["down"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               right_paddle_vel = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   elif key == simplegui.KEY_MAP["w"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               left_paddle_vel = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   elif key == simplegui.KEY_MAP["s"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               left_paddle_vel = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       def button_handler():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               new_game()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   # create frame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame = simplegui.create_frame("Pong", WIDTH, HEIGHT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame.set_draw_handler(draw)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame.set_keydown_handler(keydown)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame.set_keyup_handler(keyup)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame.add_button("Restart",button_handler)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   # start frame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   new_game()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   frame.start()

